GET http://localhost:5000/produtos

###
POST http://localhost:5000/produto

###
GET http://localhost:5000/produto/dd609687-e3c7-42aa-be5f-5d54a1f37b42

###
PUT http://localhost:5000/produto/dd609687-e3c7-42aa-be5f-5d54a1f37b42
Content-Type: 'application/json'

{
    "nome": "Nike Atualizado",
    "modelo": "Air Force 2",
    "preco": 2800
}

###
DELETE http://localhost:5000/produto/dd609687-e3c7-42aa-be5f-5d54a1f37b42
